### ISSUE TITLE
"in" keyword being erroneously recognized in bigger words (like INterfaces)

### ISSUE THREAD

**Issue by bitodt** [nir0s/sublime-logstash-syntax-highlighter#5]
In this snippet:
```
else if [host] == "71.331.22.32" {
		if [interface.description] not in
```
the "in" in "interface" is shown in red, while the "terface.description" is white.

PS: Thanks so much for this plugin!

**Comment by joaociocca** [comment]
oh, look! I can't find out how to help out with the comment toggle not working, but I think I solved this one ;D

**Comment by joaociocca** [comment]
I've been trying this one for quite a while and the only thing that seems to do the trick is moving from .tmLanguage to .sublime-syntax format. \b for boundaries won't work, \s or " " before and/or after the logical operators also won't work.
Changing to .sublime-syntax and adding boundaries does the trick, though.

Another similar issue is with escape characters inside strings:
![image](https://user-images.githubusercontent.com/6473725/74797966-39278d00-52ab-11ea-89c3-15886e0cbbc0.png)

A simple way to solve this is, again after switching to .sublime-syntax, using the default code from package, instead of the current string.text.logstash:

```
(on main)
    # Strings begin and end with quotes, and use backslashes as an escape
    # character
    - match: '"'
      scope: punctuation.definition.string.begin.logstash
      push: double_quoted_string

(outside main)
  double_quoted_string:
    - meta_scope: string.quoted.double.logstash
    - match: '\\.'
      scope: constant.character.escape.logstash
    - match: '"'
      scope: punctuation.definition.string.end.logstash
      pop: true
```

![image](https://user-images.githubusercontent.com/6473725/74798302-2c576900-52ac-11ea-8bba-99351e86d9a9.png)
